services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recipe_viewer_web
    command: ./entrypoint.sh
    volumes:
      - db_data:/app/data
      - media_data:/app/media
      - static_volume:/app/static
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DOCKER_ENV=true
      - PORT=${PORT:-8000}
      - WORKERS=${WORKERS:-4}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - SKIP_MIGRATIONS=${SKIP_MIGRATIONS:-false}
      - SKIP_COLLECTSTATIC=${SKIP_COLLECTSTATIC:-false}
    networks:
      - recipe_network

  nginx:
    image: nginx:alpine
    container_name: recipe_viewer_nginx
    ports:
      - "80:80"
    # No SSL for now because local development
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - media_data:/app/media:ro
      - static_volume:/app/static:ro
    depends_on:
      - web
    networks:
      - recipe_network

volumes:
  db_data:
  media_data:
  static_volume:

networks:
  recipe_network:
    driver: bridge
